# Generated by Django 4.2.18 on 2025-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingsession',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='typingsession',
            name='correct_words',
        ),
        migrations.RemoveField(
            model_name='typingsession',
            name='incorrect_words',
        ),
    ]
