# Generated by Django 4.2.18 on 2025-04-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_typingsession_frequency_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordperformance',
            old_name='user_input',
            new_name='target_word',
        ),
        migrations.RenameField(
            model_name='wordperformance',
            old_name='word',
            new_name='typed_word',
        ),
    ]
