# Generated by Django 4.2.18 on 2025-04-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_rename_user_input_wordperformance_target_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingsession',
            name='mode',
            field=models.CharField(choices=[('random', 'Random'), ('adaptive', 'Adaptive')], default='random', max_length=10),
        ),
        migrations.AlterField(
            model_name='wordperformance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_performances', to='fyp.typingsession'),
        ),
    ]
