# Generated by Django 4.2.18 on 2025-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0005_typingsession_mode_alter_wordperformance_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingsession',
            name='mode',
            field=models.CharField(default='random', max_length=10),
        ),
    ]
