# Generated by Django 4.2.18 on 2025-04-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0002_rename_date_typingsession_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingsession',
            name='frequency_rank',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='typingsession',
            name='max_word_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='typingsession',
            name='min_word_length',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='WordPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('user_input', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('backspace_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_performance', to='fyp.typingsession')),
            ],
        ),
    ]
